on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Doozers/depviz-action@8cbbbeb05b5d77ca665637ec642f66238b729285
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-targets: 'moul/depviz-test gnolang/roadmap'
          json-output: 'res.json'
      
      - uses: Doozers/depviz-action@8cbbbeb05b5d77ca665637ec642f66238b729285
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generation-targets: 'gnolang/roadmap'
          json-output: 'roadmap.json'
