name: depviz

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: depviz-generate
      # fetch only
      - uses: moul/depviz-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          targets: 'moul/depviz-test gnolang/roadmap'
      
      # gen roadmap1.json
      - uses: moul/depviz-action@main
        with:
          targets: gnolang/roadmap
          json-output: roadmap1.json
          png-output: roadmap1.png
          svg-output: roadmap1.svg

      # gen roadmap2.json
      - uses: moul/depviz-action@main
        with:
          targets: moul/depviz-test
          json-output: roadmap2.json
          png-output: roadmap2.png
          svg-output: roadmap2.svg
          
      
      # publish on a branch
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:          
          GITHUB_TOKEN: $GITHUB_TOKEN
        with:
          ##file_pattern: "${{ inputs.json-output }} ${{ inputs.png-output }} ${{ inputs.svg-output }} ${{ inputs.csv-output }}"
          file_pattern: 'roadmap1.json roadmap2.json'
          commit_message: 'build: generate'
          branch: 'depviz-generate'
          push_options: '--force'      

