on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Doozers/depviz-action@b314e1221b1c973adb7bff9fb81d138194bab4ee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          targets: 'moul/depviz-test gnolang/roadmap'
          json-output: 'res.json'
